# THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
# APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
# HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
# OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
# IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
# ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

# IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
# WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
# THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
# GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
# USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
# DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
# PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
# EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGES.

# Copyright (c) 2018 Dr. Oliver Barth <info@drb-electronic.de>
# Global layout parameter

DRBLAYOUT_frmPadding = 5
DRBLAYOUT_frmIntPadding = 3
DRBLAYOUT_CompPadding = 3
DRBLAYOUT_frmBackground = 'Light Gray'
DRBLAYOUT_labelFrmBackground = 'lavender'
DRBLAYOUT_butBackground = 'whitesmoke'
DRBLAYOUT_pythonKW = 'red'
DRBLAYOUT_appKW = 'green'
DRBLAYOUT_actLine = 'blue'
DRBLAYOUT_breakpoint = 'yellow'
DRBLAYOUT_comment = 'orange'
DRBLAYOUT_error = 'red'
DRBLAYOUT_tab1 = 'lavender'
DRBLAYOUT_tab2 = 'white'
DRBLAYOUT_font = 'Calibri 8'
DRBLAYOUT_header_font = 'Calibri 10'
DRBLAYOUT_frameGeometry = '2000x900'
DRBLAYOUT_AppTitle = 'drb OIPC PYFFAU - v0.2.2'

# editor stile dark blue
DRBLAYOUT_editor_backgroud = 'midnightblue'
DRBLAYOUT_editor_text = 'white'
DRBLAYOUT_editor_pythonKW = 'yellow'
DRBLAYOUT_editor_appKW = 'cyan'
DRBLAYOUT_editor_comment = 'cornflowerblue'
DRBLAYOUT_editor_tab1 = 'darkblue'
DRBLAYOUT_editor_tab2 = 'darkblue'
