version: 1

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(threadName)s %(message)s'

handlers:
  api_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/api.log
    maxBytes: 5000000
    backupCount: 3
    formatter: json

  stock_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/stock.log
    maxBytes: 5000000
    backupCount: 3
    formatter: json

  model_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/model.log
    maxBytes: 5000000
    backupCount: 3
    formatter: json

loggers:
  api:
    level: INFO
    handlers: [api_file]
    propagate: false

  stock:
    level: INFO
    handlers: [stock_file]
    propagate: false

  model:
    level: INFO
    handlers: [model_file]
    propagate: false

root:
  level: WARNING
  handlers: []

